version: '3.8'

services:
  translation:
    build: ./translation-service
    ports:
      - "8003:8003"
    environment:
      - PORT=8003

  summarization:
    build: ./summarization-service
    ports:
      - "8001:8001"
    environment:
      - PORT=8001

  user-service:
    build: ./user-service
    ports:
      - "8002:8002"
    environment:
      - PORT=8002